# fly.toml app configuration file generated for mail-tales-server on 2024-09-02T09:39:04+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mail-tales-server'
primary_region = 'ams'

[build]

[http_service]
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
